import Head from "next/head";
import Navbar from "../components/Navbar";
import SearchBar from "../components/SearchBar";
import ExpenseBar from "../components/ExpenseBar";
import ExpenseList from "../components/ExpenseList";

export default function Home() {
  return (
    <div className={`bg-[#E7EBF0] h-screen`}>
      <Head>
        <title>Expense Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito:wght@500&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main className="flex flex-col p-4">
        <SearchBar />
        <ExpenseBar availableAmount={90} spentAmount={90} />
        <ExpenseList />
      </main>
      <footer>
        <Navbar />
      </footer>
    </div>
  );
}
